#!/bin/bash

# add ppas
sudo add-apt-repository -y ppa:canonical-kernel-team/proposed
sudo add-apt-repository -y ppa:ubuntu-tegra/kernel-daily
sudo apt update

# install ssl for kernels
sudo apt-get install libssl-dev -y

# add CUDA to path
cat <<EOT >> $HOME/.bashrc
if [ -d /usr/local/cuda-12.2 ];
then
	export PATH=/usr/local/cuda-12.2/bin:\$PATH
	export LD_LIBRARY_PATH=/usr/local/cuda-12.2/lib64
fi
EOT
