#!/bin/bash

set -e

if [ $# -gt 1 ]; then
	echo "USAGE: $0 [-x]"
	exit 1
fi

ALREADY_EXTRACTED=0
if [ $# -eq 1 ]; then
	if [[ "$1" == "-x" ]]; then
		ALREADY_EXTRACTED=1
	else
		echo "Unrecognized option '$1'"
		exit 1
	fi
fi

SCRIPTDIR=$(dirname "$(readlink -f "$0")")
TOPDIR=$(realpath "$SCRIPTDIR/..")
cd $TOPDIR

USERNAME=ubuntu

echo "Installing dependencies..."
sudo apt install -yqq lbzip2 qemu-user-static pv

rootfs=$TOPDIR/Linux_for_Tegra/rootfs
if [ $ALREADY_EXTRACTED -eq 0 ]; then
	if [ ! -d Linux_for_Tegra ]; then
		echo "Extracting BSP..."
		pv $(ls | grep -iE "jetson_linux_.*_aarch64\.tbz2" | head -1) | tar -xj
	fi

	# if rootfs/ doesn't exist or only has one file (README.txt) then extract
	if [ ! -d $rootfs ] || [ "$(ls -A $rootfs | wc -l)" -le 1 ]; then
		echo "Extracting rootfs. This may take a while..."
		mkdir -p $rootfs
		pv $(ls | grep -iE "tegra_linux_sample-root-filesystem_.*_aarch64\.tbz2" | head -1) | sudo tar -xpj -C $rootfs
		echo "Done extracting rootfs. Applying binaries..."
	fi
fi

cd Linux_for_Tegra
# Use OpenRM if available
if ./apply_binaries.sh --help | grep -q -- --openrm; then
	OPENRM_FLAG="--openrm"
fi
sudo ./apply_binaries.sh $OPENRM_FLAG
echo "Done applying binaries."
./tools/l4t_flash_prerequisites.sh
sudo tools/l4t_create_default_user.sh -u $USERNAME -p $USERNAME -n jetpack -a --accept-license
# put files in rootfs
userhome=$rootfs/home/$USERNAME
sudo cp $SCRIPTDIR/grub-setup $userhome
sudo cp $SCRIPTDIR/autosetup $userhome
echo "%sudo ALL=(ALL) NOPASSWD: ALL" | sudo tee -a $rootfs/etc/sudoers
echo "2>&1 resize > /dev/null" >> $userhome/.bashrc
cp -r $HOME/.ssh $userhome/

if [ -f $HOME/.ssh/id_ed25519.pub ]; then
	if ! grep -q -F "$(cat $HOME/.ssh/id_ed25519.pub)" $userhome/.ssh/authorized_keys; then
		cat $HOME/.ssh/id_ed25519.pub >> $userhome/.ssh/authorized_keys
	fi
fi

if [ -f /root/.ssh/id_ed25519.pub ]; then
	sudo cat /root/.ssh/id_ed25519.pub >> $userhome/.ssh/authorized_keys
fi

echo "Success!"
